### ISSUE TITLE
Code is breaking when VM/CT is turned off while script runs

### ISSUE THREAD

**Issue by ojsef39** [ojsef39/uptimekuma-maintenance-mode-api#26]
Code does not find  a hostname and throws an error that breaks the code, something about "hostname not assigned" or something like that

**Comment by ojsef39** [comment]
```
INFO: HOOK: backup-end stop 103
INFO: HOOK: Running backup-end uptime.py (END)
INFO: /usr/lib/python3/dist-packages/urllib3/connectionpool.py:1015: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.18.100.3'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
INFO:   warnings.warn(
INFO: /usr/lib/python3/dist-packages/urllib3/connectionpool.py:1015: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.18.100.3'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
INFO:   warnings.warn(
INFO: /usr/lib/python3/dist-packages/urllib3/connectionpool.py:1015: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.18.100.3'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
INFO:   warnings.warn(
INFO: 2023-09-07 00:09:09,168 - WARNING - Something went wrong getting ip of: 103
INFO: 2023-09-07 00:09:09,168 - WARNING - There was an error while using proxmox api.
INFO: Traceback (most recent call last):
INFO:   File "/root/uptime-api.py", line 358, in <module>
INFO:     main()
INFO:   File "/root/uptime-api.py", line 353, in main
INFO:     get_mm()
INFO:   File "/root/uptime-api.py", line 228, in get_mm
INFO:     parse_mm(mm['id'], mm['description'], mm['title'])
INFO:   File "/root/uptime-api.py", line 236, in parse_mm
INFO:     change_mm(tag, mm_id, mm_title)
INFO:   File "/root/uptime-api.py", line 243, in change_mm
INFO:     mm_end(mm_id, mm_title)
INFO:   File "/root/uptime-api.py", line 258, in mm_end
INFO:     change_mm_end(mm_id, mm_title)
INFO:   File "/root/uptime-api.py", line 295, in change_mm_end
INFO:     if hostname is None:
INFO: NameError: name 'hostname' is not defined
```
